// Code automatically generated by 'Generate Cone Mapping Model' script by Jolyon Troscianko

//Model fits:
//lw 0.9958659724871565
//mw 0.9942983806036647
//sw 0.9960584368900831
//dbl 0.9954235587498417


// Generated: 2019/10/28   13:27:33


import ij.*;
import ij.plugin.filter.PlugInFilter;
import ij.process.*;

public class Butterfly_Scanner_Linear_Bluetit_LMS_D65_ implements PlugInFilter {

ImageStack stack;
	public int setup(String arg, ImagePlus imp) { 
	stack = imp.getStack(); 
	return DOES_32 + STACK_REQUIRED; 
	}
public void run(ImageProcessor ip) {

IJ.showStatus("Cone Mapping");
float[] visibleR;
float[] visibleG;
float[] visibleB;
int w = stack.getWidth();
int h = stack.getHeight();
int dimension = w*h;

float[] lw = new float[dimension];
float[] mw = new float[dimension];
float[] sw = new float[dimension];
float[] dbl = new float[dimension];

visibleR = (float[]) stack.getPixels(1);
visibleG = (float[]) stack.getPixels(2);
visibleB = (float[]) stack.getPixels(3);

for (int i=0;i<dimension;i++) {
lw[i] = (float) (0.015781493219278256 +(visibleR[i]*0.008832263293211821)+(visibleG[i]*0.0027688115032297356)+(visibleB[i]*-7.728509262279501E-4)+(visibleR[i]*visibleG[i]*-3.239216857968333E-5)+(visibleR[i]*visibleB[i]*-1.7745551878084746E-5)+(visibleG[i]*visibleB[i]*3.628312058269961E-5));
mw[i] = (float) (0.015742093076459834 +(visibleR[i]*-1.4226254316926796E-4)+(visibleG[i]*0.010981208882665685)+(visibleB[i]*-6.953635645127854E-4)+(visibleR[i]*visibleG[i]*-5.09561595954159E-6)+(visibleR[i]*visibleB[i]*5.749646508572346E-6)+(visibleG[i]*visibleB[i]*-6.207090537009321E-6));
sw[i] = (float) (0.009580950348434586 +(visibleR[i]*1.403718922272862E-4)+(visibleG[i]*1.7553675394871944E-4)+(visibleB[i]*0.01049001042348981)+(visibleR[i]*visibleG[i]*7.286210416165357E-6)+(visibleR[i]*visibleB[i]*-5.531215138477047E-5)+(visibleG[i]*visibleB[i]*3.197028374099269E-5));
dbl[i] = (float) (0.013336985700231115 +(visibleR[i]*0.002466685656962072)+(visibleG[i]*0.006955606716485541)+(visibleB[i]*0.0010356783506816531)+(visibleR[i]*visibleG[i]*-1.2520750785814373E-5)+(visibleR[i]*visibleB[i]*-1.7359831671397726E-5)+(visibleG[i]*visibleB[i]*2.084653571283712E-5));
IJ.showProgress((float) i/dimension);
}

ImageStack outStack = new ImageStack(w, h);
outStack.addSlice("lw", lw);
outStack.addSlice("mw", mw);
outStack.addSlice("sw", sw);
outStack.addSlice("dbl", dbl);
new ImagePlus("Output", outStack).show();

}
}
