// Code automatically generated by 'Generate Cone Mapping Model' script by Jolyon Troscianko

//Model fits:
//lw 0.9915271030031151
//mw 0.99239566639017
//sw 0.997587985918585
//dbl 0.9946134744964883


// Generated: 2019/8/12   4:42:46


import ij.*;
import ij.plugin.filter.PlugInFilter;
import ij.process.*;

public class CameraID_Bluetit_LMS_D65_ implements PlugInFilter {

ImageStack stack;
	public int setup(String arg, ImagePlus imp) { 
	stack = imp.getStack(); 
	return DOES_32 + STACK_REQUIRED; 
	}
public void run(ImageProcessor ip) {

IJ.showStatus("Cone Mapping");
float[] visibleR;
float[] visibleG;
float[] visibleB;
int w = stack.getWidth();
int h = stack.getHeight();
int dimension = w*h;

float[] lw = new float[dimension];
float[] mw = new float[dimension];
float[] sw = new float[dimension];
float[] dbl = new float[dimension];

visibleR = (float[]) stack.getPixels(1);
visibleG = (float[]) stack.getPixels(2);
visibleB = (float[]) stack.getPixels(3);

for (int i=0;i<dimension;i++) {
lw[i] = (float) (-0.009106382651760187 +(visibleR[i]*0.009707172438247478)+(visibleG[i]*9.230689696771972E-5)+(visibleB[i]*4.8729486722011954E-4)+(visibleR[i]*visibleG[i]*5.045124450904427E-5)+(visibleR[i]*visibleB[i]*-3.336180515794706E-5)+(visibleG[i]*visibleB[i]*-1.7632669286290885E-5));
mw[i] = (float) (-0.001345048477690609 +(visibleR[i]*-5.645098410897769E-4)+(visibleG[i]*0.012654274210594599)+(visibleB[i]*-0.002222452107064011)+(visibleR[i]*visibleG[i]*7.290469006330116E-6)+(visibleR[i]*visibleB[i]*1.4416335104640082E-5)+(visibleG[i]*visibleB[i]*-1.889408484133201E-5));
sw[i] = (float) (0.0054823874601928795 +(visibleR[i]*-1.23834312332851E-4)+(visibleG[i]*0.0017605904797011274)+(visibleB[i]*0.008191019935867868)+(visibleR[i]*visibleG[i]*-4.788148988903709E-7)+(visibleR[i]*visibleB[i]*-2.8113376706774834E-5)+(visibleG[i]*visibleB[i]*2.6566458263991505E-5));
dbl[i] = (float) (-0.004221911938768405 +(visibleR[i]*0.002463929131423345)+(visibleG[i]*0.007444693385657597)+(visibleB[i]*1.0592179679534161E-4)+(visibleR[i]*visibleG[i]*1.4597392338011945E-5)+(visibleR[i]*visibleB[i]*-1.293652472617858E-5)+(visibleG[i]*visibleB[i]*-3.12595542584765E-7));
IJ.showProgress((float) i/dimension);
}

ImageStack outStack = new ImageStack(w, h);
outStack.addSlice("lw", lw);
outStack.addSlice("mw", mw);
outStack.addSlice("sw", sw);
outStack.addSlice("dbl", dbl);
new ImagePlus("Output", outStack).show();

}
}
