// Code automatically generated by 'Generate Cone Mapping Model' script by Jolyon Troscianko

//Model fits:
//rh3 0.998061535729418
//rh4 0.9971688817440344
//rh5 0.996144845988356
//rh6 0.9998326580978566
//rh1UVAP 0.9997786502150109


// Generated: 2019/5/25   14:29:45


import ij.*;
import ij.plugin.filter.PlugInFilter;
import ij.process.*;

public class Canon_7D_Novoflex_35mm_D65_to_Drosophila_D65 implements PlugInFilter {

ImageStack stack;
	public int setup(String arg, ImagePlus imp) { 
	stack = imp.getStack(); 
	return DOES_32 + STACK_REQUIRED; 
	}
public void run(ImageProcessor ip) {

IJ.showStatus("Cone Mapping");
float[] vR;
float[] vG;
float[] vB;
float[] uB;
float[] uR;
int w = stack.getWidth();
int h = stack.getHeight();
int dimension = w*h;

float[] rh3 = new float[dimension];
float[] rh4 = new float[dimension];
float[] rh5 = new float[dimension];
float[] rh6 = new float[dimension];
float[] rh1UVAP = new float[dimension];

vR = (float[]) stack.getPixels(1);
vG = (float[]) stack.getPixels(2);
vB = (float[]) stack.getPixels(3);
uB = (float[]) stack.getPixels(4);
uR = (float[]) stack.getPixels(5);

for (int i=0;i<dimension;i++) {
rh3[i] = (float) (-0.0016345560031606338 +(vR[i]*2.54397918226986E-4)+(vG[i]*-3.746137079531737E-4)+(vB[i]*5.020917318073032E-4)+(uB[i]*-0.0036434612403440396)+(uR[i]*0.013180254259050403)+(vR[i]*vG[i]*-2.3985846911351685E-6)+(vR[i]*vB[i]*-4.256208174500691E-6)+(vR[i]*uB[i]*1.1762482165020343E-5)+(vR[i]*uR[i]*-2.1392277743392966E-5)+(vG[i]*vB[i]*3.020987078112949E-6)+(vG[i]*uB[i]*-2.035415365884197E-6)+(vG[i]*uR[i]*2.0958657377172193E-5)+(vB[i]*uB[i]*-2.4849970493012175E-5)+(vB[i]*uR[i]*2.668195513362822E-5)+(uB[i]*uR[i]*-7.711373543386601E-6));
rh4[i] = (float) (0.001110729214411945 +(vR[i]*3.759449825618849E-4)+(vG[i]*-0.0013168641812762896)+(vB[i]*0.0022079476157015917)+(uB[i]*0.00557521502137258)+(uR[i]*0.003045128193437081)+(vR[i]*vG[i]*-4.2930261936935754E-7)+(vR[i]*vB[i]*1.0854220261719929E-6)+(vR[i]*uB[i]*1.0121148493195756E-6)+(vR[i]*uR[i]*-1.619937219401435E-5)+(vG[i]*vB[i]*-4.225953760581124E-6)+(vG[i]*uB[i]*-7.186868708380495E-5)+(vG[i]*uR[i]*8.657777379806811E-5)+(vB[i]*uB[i]*1.0625665614297373E-4)+(vB[i]*uR[i]*-9.530702829383341E-5)+(uB[i]*uR[i]*-6.334134583872447E-6));
rh5[i] = (float) (0.003959470841579645 +(vR[i]*5.790029074480839E-4)+(vG[i]*-0.004109941078898419)+(vB[i]*0.010989118364510072)+(uB[i]*0.004382869999598753)+(uR[i]*-0.0021213838947675024)+(vR[i]*vG[i]*3.4858899653553535E-7)+(vR[i]*vB[i]*4.124190044511872E-6)+(vR[i]*uB[i]*-2.9020041391688708E-5)+(vR[i]*uR[i]*2.1792386709773626E-5)+(vG[i]*vB[i]*-8.010374672294695E-6)+(vG[i]*uB[i]*-8.555923103366336E-5)+(vG[i]*uR[i]*7.999634513375641E-5)+(vB[i]*uB[i]*1.6447848511570712E-4)+(vB[i]*uR[i]*-1.4791503052064445E-4)+(uB[i]*uR[i]*2.455820998522555E-6));
rh6[i] = (float) (-4.491354056772541E-4 +(vR[i]*-0.0013685460053785739)+(vG[i]*0.0059902378699273305)+(vB[i]*0.005452051635049002)+(uB[i]*-3.649100706598818E-4)+(uR[i]*3.867915453723787E-4)+(vR[i]*vG[i]*-2.2796856052832586E-7)+(vR[i]*vB[i]*2.075431596006388E-6)+(vR[i]*uB[i]*2.3203763256136145E-5)+(vR[i]*uR[i]*-2.8601727441586395E-5)+(vG[i]*vB[i]*-2.2088463502252897E-6)+(vG[i]*uB[i]*-2.3594910947754273E-5)+(vG[i]*uR[i]*3.705463767812025E-5)+(vB[i]*uB[i]*-5.413154168172393E-7)+(vB[i]*uR[i]*-7.19270362641314E-6)+(uB[i]*uR[i]*-1.112399703325543E-6));
rh1UVAP[i] = (float) (-6.868804085548748E-5 +(vR[i]*-3.484643405564116E-4)+(vG[i]*1.62262091730372E-4)+(vB[i]*0.007081580742003266)+(uB[i]*1.5967966065718122E-4)+(uR[i]*0.002928986986651163)+(vR[i]*vG[i]*-9.654630987228572E-7)+(vR[i]*vB[i]*1.4606235600073435E-6)+(vR[i]*uB[i]*6.6949196147943605E-6)+(vR[i]*uR[i]*-1.2825730511498335E-5)+(vG[i]*vB[i]*-1.8926347101634852E-6)+(vG[i]*uB[i]*-2.6264520423773687E-5)+(vG[i]*uR[i]*3.6334018303925116E-5)+(vB[i]*uB[i]*2.7360680024881365E-5)+(vB[i]*uR[i]*-2.897113985970663E-5)+(uB[i]*uR[i]*-1.044936404114803E-6));
IJ.showProgress((float) i/dimension);
}

ImageStack outStack = new ImageStack(w, h);
outStack.addSlice("rh3", rh3);
outStack.addSlice("rh4", rh4);
outStack.addSlice("rh5", rh5);
outStack.addSlice("rh6", rh6);
outStack.addSlice("rh1UVAP", rh1UVAP);
new ImagePlus("Output", outStack).show();

}
}
