// Code automatically generated by 'Generate Cone Mapping Model' script by Jolyon Troscianko

//Model fits:
//lw 0.9993093225218918
//mw 0.9960007564739821
//sw 0.9933676628270148
//dbl 0.9993201584528555


// Generated: 2019/3/26   15:1:54


import ij.*;
import ij.plugin.filter.PlugInFilter;
import ij.process.*;

public class Canon_700D_18_to_55mm_D65_to_Peafowl_LMS_D65 implements PlugInFilter {

ImageStack stack;
	public int setup(String arg, ImagePlus imp) { 
	stack = imp.getStack(); 
	return DOES_32 + STACK_REQUIRED; 
	}
public void run(ImageProcessor ip) {

IJ.showStatus("Cone Mapping");
float[] r;
float[] g;
float[] b;
int w = stack.getWidth();
int h = stack.getHeight();
int dimension = w*h;

float[] lw = new float[dimension];
float[] mw = new float[dimension];
float[] sw = new float[dimension];
float[] dbl = new float[dimension];

r = (float[]) stack.getPixels(1);
g = (float[]) stack.getPixels(2);
b = (float[]) stack.getPixels(3);

for (int i=0;i<dimension;i++) {
lw[i] = (float) (-0.006563875466306046 +(r[i]*0.01284994830685434)+(g[i]*-0.002011887669742719)+(b[i]*-7.581136032890814E-4)+(r[i]*g[i]*-1.5892349866065426E-5)+(r[i]*b[i]*1.7856965779158496E-5)+(g[i]*b[i]*-1.443011937222245E-6));
mw[i] = (float) (0.009327720504453636 +(r[i]*-3.0243150308885116E-4)+(g[i]*0.015755661767984402)+(b[i]*-0.006073919987639593)+(r[i]*g[i]*1.7793392119995917E-6)+(r[i]*b[i]*-2.7703007995997374E-5)+(g[i]*b[i]*3.0340944572638565E-5));
sw[i] = (float) (-0.006736087877283329 +(r[i]*-0.002577421832335106)+(g[i]*0.007484610281033045)+(b[i]*0.005977266663227042)+(r[i]*g[i]*7.240516778571776E-6)+(r[i]*b[i]*8.075079517634854E-6)+(g[i]*b[i]*-2.2481928143759894E-5));
dbl[i] = (float) (0.001137053166338761 +(r[i]*0.003217604271116619)+(g[i]*0.009744205554812663)+(b[i]*-0.003194897239379819)+(r[i]*g[i]*-4.436751169536892E-6)+(r[i]*b[i]*-6.929497917933072E-6)+(g[i]*b[i]*1.362257467628407E-5));
IJ.showProgress((float) i/dimension);
}

ImageStack outStack = new ImageStack(w, h);
outStack.addSlice("lw", lw);
outStack.addSlice("mw", mw);
outStack.addSlice("sw", sw);
outStack.addSlice("dbl", dbl);
new ImagePlus("Output", outStack).show();

}
}
