// Code automatically generated by 'Generate Cone Mapping Model' script by Jolyon Troscianko

//Model fits:
//lw 0.9917456392294026
//mw 0.9965248499401709
//sw 0.9899804250629369
//dbl 0.9922916324864015


// Generated: 2019/9/14   14:31:24


import ij.*;
import ij.plugin.filter.PlugInFilter;
import ij.process.*;

public class Chameleon_Chameleon_C_dilepis_V_D65_ implements PlugInFilter {

ImageStack stack;
	public int setup(String arg, ImagePlus imp) { 
	stack = imp.getStack(); 
	return DOES_32 + STACK_REQUIRED; 
	}
public void run(ImageProcessor ip) {

IJ.showStatus("Cone Mapping");
float[] visibleR;
float[] visibleG;
float[] visibleB;
int w = stack.getWidth();
int h = stack.getHeight();
int dimension = w*h;

float[] lw = new float[dimension];
float[] mw = new float[dimension];
float[] sw = new float[dimension];
float[] dbl = new float[dimension];

visibleR = (float[]) stack.getPixels(1);
visibleG = (float[]) stack.getPixels(2);
visibleB = (float[]) stack.getPixels(3);

for (int i=0;i<dimension;i++) {
lw[i] = (float) (0.016024477146363913 +(visibleR[i]*0.003183756878153628)+(visibleG[i]*0.004922690046634111)+(visibleB[i]*5.188496485379165E-4)+(visibleR[i]*visibleG[i]*5.118141129801155E-5)+(visibleR[i]*visibleB[i]*1.4301208686457426E-7)+(visibleG[i]*visibleB[i]*-3.789126478172165E-5));
mw[i] = (float) (0.009249536707371454 +(visibleR[i]*-2.3986481976913092E-4)+(visibleG[i]*0.008969734972467894)+(visibleB[i]*8.069889544323525E-4)+(visibleR[i]*visibleG[i]*-7.658154417848609E-7)+(visibleR[i]*visibleB[i]*2.062984402943732E-5)+(visibleG[i]*visibleB[i]*-1.6459489532752723E-5));
sw[i] = (float) (0.003063854174137482 +(visibleR[i]*4.101560231835186E-4)+(visibleG[i]*0.0017442949607263283)+(visibleB[i]*0.006970736333833831)+(visibleR[i]*visibleG[i]*-1.5769769067896282E-5)+(visibleR[i]*visibleB[i]*1.3269267530506262E-5)+(visibleG[i]*visibleB[i]*6.720010087077413E-6));
dbl[i] = (float) (0.014895529396348613 +(visibleR[i]*0.003035115228259543)+(visibleG[i]*0.004816470224922916)+(visibleB[i]*8.441911199359354E-4)+(visibleR[i]*visibleG[i]*4.5698125407169135E-5)+(visibleR[i]*visibleB[i]*-3.634680809026049E-7)+(visibleG[i]*visibleB[i]*-3.258742329531389E-5));
IJ.showProgress((float) i/dimension);
}

ImageStack outStack = new ImageStack(w, h);
outStack.addSlice("lw", lw);
outStack.addSlice("mw", mw);
outStack.addSlice("sw", sw);
outStack.addSlice("dbl", dbl);
new ImagePlus("Output", outStack).show();

}
}
