// Code automatically generated by 'Generate Cone Mapping Model' script by Jolyon Troscianko

//Model fits:
//rh3 0.9965024761980057
//rh4 0.9977921786513954
//rh5 0.9972416908791227
//rh6 0.9977170764587223
//rh1UVAP 0.998482134494578


// Generated: 2019/7/1   13:20:20


import ij.*;
import ij.plugin.filter.PlugInFilter;
import ij.process.*;

public class eIm_52mm_Drosophila_D65_ implements PlugInFilter {

ImageStack stack;
	public int setup(String arg, ImagePlus imp) { 
	stack = imp.getStack(); 
	return DOES_32 + STACK_REQUIRED; 
	}
public void run(ImageProcessor ip) {

IJ.showStatus("Cone Mapping");
float[] visibleR;
float[] visibleG;
float[] visibleB;
float[] uvB;
float[] uvR;
int w = stack.getWidth();
int h = stack.getHeight();
int dimension = w*h;

float[] rh3 = new float[dimension];
float[] rh4 = new float[dimension];
float[] rh5 = new float[dimension];
float[] rh6 = new float[dimension];
float[] rh1UVAP = new float[dimension];

visibleR = (float[]) stack.getPixels(1);
visibleG = (float[]) stack.getPixels(2);
visibleB = (float[]) stack.getPixels(3);
uvB = (float[]) stack.getPixels(4);
uvR = (float[]) stack.getPixels(5);

for (int i=0;i<dimension;i++) {
rh3[i] = (float) (-0.002132346284421609 +(visibleR[i]*-1.0663841158467763E-4)+(visibleG[i]*4.2143149623669995E-4)+(visibleB[i]*3.650238584550458E-4)+(uvB[i]*-0.009121590264716992)+(uvR[i]*0.0185186097086353)+(visibleR[i]*visibleG[i]*-1.9052657208840195E-5)+(visibleR[i]*visibleB[i]*6.390509834112157E-5)+(visibleR[i]*uvB[i]*1.0245013807853432E-4)+(visibleR[i]*uvR[i]*-1.4529848813892303E-4)+(visibleG[i]*visibleB[i]*-2.9635707596021283E-5)+(visibleG[i]*uvB[i]*-4.974999792825494E-4)+(visibleG[i]*uvR[i]*5.242100735185634E-4)+(visibleB[i]*uvB[i]*3.4317621985337346E-4)+(visibleB[i]*uvR[i]*-3.3946484792374683E-4)+(uvB[i]*uvR[i]*3.8627521057016E-7));
rh4[i] = (float) (-0.004656718356006487 +(visibleR[i]*4.2177093762796924E-5)+(visibleG[i]*-0.0012952387325424826)+(visibleB[i]*0.0029473078189786203)+(uvB[i]*-0.002348132231685858)+(uvR[i]*0.011224948259887653)+(visibleR[i]*visibleG[i]*-8.829773611087706E-6)+(visibleR[i]*visibleB[i]*7.670335586523393E-5)+(visibleR[i]*uvB[i]*8.049061539822284E-6)+(visibleR[i]*uvR[i]*-7.811403587712602E-5)+(visibleG[i]*visibleB[i]*-3.521516532869105E-5)+(visibleG[i]*uvB[i]*-2.2025026939979353E-4)+(visibleG[i]*uvR[i]*2.8426479003180604E-4)+(visibleB[i]*uvB[i]*3.4664728159122967E-4)+(visibleB[i]*uvR[i]*-4.2917429939438433E-4)+(uvB[i]*uvR[i]*5.603614776959118E-5));
rh5[i] = (float) (-0.0025535318326314156 +(visibleR[i]*2.7476024350044396E-4)+(visibleG[i]*-0.004278653240350733)+(visibleB[i]*0.012064344069672777)+(uvB[i]*-0.0036308577886425015)+(uvR[i]*0.0059475108028656624)+(visibleR[i]*visibleG[i]*5.04103221887684E-6)+(visibleR[i]*visibleB[i]*7.059853844574793E-5)+(visibleR[i]*uvB[i]*4.102865785003008E-5)+(visibleR[i]*uvR[i]*-1.1524032759628245E-4)+(visibleG[i]*visibleB[i]*-3.586021547331758E-5)+(visibleG[i]*uvB[i]*-2.0246770200014482E-4)+(visibleG[i]*uvR[i]*2.812404548628745E-4)+(visibleB[i]*uvB[i]*3.524426164636144E-4)+(visibleB[i]*uvR[i]*-4.669828086296948E-4)+(uvB[i]*uvR[i]*8.045283947553532E-5));
rh6[i] = (float) (-0.006039808411909205 +(visibleR[i]*-0.0010036863915925068)+(visibleG[i]*0.007346772553308364)+(visibleB[i]*0.0049453499351466736)+(uvB[i]*0.0036485765567028793)+(uvR[i]*-0.003909148464092547)+(visibleR[i]*visibleG[i]*-1.2268176155760985E-5)+(visibleR[i]*visibleB[i]*-2.6958781254594775E-5)+(visibleR[i]*uvB[i]*-4.521420923723081E-6)+(visibleR[i]*uvR[i]*3.0350103849449977E-5)+(visibleG[i]*visibleB[i]*2.361961463003148E-5)+(visibleG[i]*uvB[i]*9.889186699025927E-5)+(visibleG[i]*uvR[i]*-1.3168157898363073E-4)+(visibleB[i]*uvB[i]*-2.7150679339554997E-4)+(visibleB[i]*uvR[i]*3.1096531890099715E-4)+(uvB[i]*uvR[i]*-2.193705879099797E-5));
rh1UVAP[i] = (float) (-0.0036467746134887756 +(visibleR[i]*-3.704936792912692E-4)+(visibleG[i]*0.001043481692339794)+(visibleB[i]*0.007082509562386025)+(uvB[i]*-0.0010142841510661167)+(uvR[i]*0.0038503538771871037)+(visibleR[i]*visibleG[i]*-8.323787203695128E-6)+(visibleR[i]*visibleB[i]*1.2185489657811716E-5)+(visibleR[i]*uvB[i]*1.63110894427712E-5)+(visibleR[i]*uvR[i]*-2.7360005040069398E-5)+(visibleG[i]*visibleB[i]*6.859217630486005E-7)+(visibleG[i]*uvB[i]*-6.57767283473237E-5)+(visibleG[i]*uvR[i]*7.383628359636719E-5)+(visibleB[i]*uvB[i]*-2.122921934634369E-5)+(visibleB[i]*uvR[i]*1.3842686148368357E-5)+(uvB[i]*uvR[i]*7.782173412802206E-6));
IJ.showProgress((float) i/dimension);
}

ImageStack outStack = new ImageStack(w, h);
outStack.addSlice("rh3", rh3);
outStack.addSlice("rh4", rh4);
outStack.addSlice("rh5", rh5);
outStack.addSlice("rh6", rh6);
outStack.addSlice("rh1UVAP", rh1UVAP);
new ImagePlus("Output", outStack).show();

}
}
