// Code automatically generated by 'Generate Cone Mapping Model' script by Jolyon Troscianko

//Model fits:
//lw 0.9920371276163448
//mw 0.9927357244256739
//sw 0.9934554353456674
//dbl 0.9945714101671074


// Generated: 2019/3/26   15:3:48


import ij.*;
import ij.plugin.filter.PlugInFilter;
import ij.process.*;

public class Michal700D_Peafowl_LMS_D65_ implements PlugInFilter {

ImageStack stack;
	public int setup(String arg, ImagePlus imp) { 
	stack = imp.getStack(); 
	return DOES_32 + STACK_REQUIRED; 
	}
public void run(ImageProcessor ip) {

IJ.showStatus("Cone Mapping");
float[] visibleR;
float[] visibleG;
float[] visibleB;
int w = stack.getWidth();
int h = stack.getHeight();
int dimension = w*h;

float[] lw = new float[dimension];
float[] mw = new float[dimension];
float[] sw = new float[dimension];
float[] dbl = new float[dimension];

visibleR = (float[]) stack.getPixels(1);
visibleG = (float[]) stack.getPixels(2);
visibleB = (float[]) stack.getPixels(3);

for (int i=0;i<dimension;i++) {
lw[i] = (float) (0.001242786426050545 +(visibleR[i]*0.012133890002005415)+(visibleG[i]*-0.0023811536629181284)+(visibleB[i]*6.843647087261504E-4)+(visibleR[i]*visibleG[i]*7.41498581273473E-5)+(visibleR[i]*visibleB[i]*-8.934183317951407E-5)+(visibleG[i]*visibleB[i]*1.1371992780938724E-5));
mw[i] = (float) (0.014812187788202903 +(visibleR[i]*-0.0024394401099586626)+(visibleG[i]*0.016049038258597943)+(visibleB[i]*-0.0033894112503433794)+(visibleR[i]*visibleG[i]*6.930468318573913E-5)+(visibleR[i]*visibleB[i]*-4.5948135746359846E-5)+(visibleG[i]*visibleB[i]*-2.7403952258784746E-5));
sw[i] = (float) (0.01034506117735012 +(visibleR[i]*8.59381130925477E-5)+(visibleG[i]*0.0036385474402974263)+(visibleB[i]*0.0064318139080760265)+(visibleR[i]*visibleG[i]*-1.4776099422533864E-5)+(visibleR[i]*visibleB[i]*-7.260749626317979E-5)+(visibleG[i]*visibleB[i]*8.232018273006954E-5));
dbl[i] = (float) (0.008649666781112042 +(visibleR[i]*0.0020056493817241024)+(visibleG[i]*0.00924016801299513)+(visibleB[i]*-0.0010468813784646873)+(visibleR[i]*visibleG[i]*6.358470142047561E-5)+(visibleR[i]*visibleB[i]*-6.789670164139157E-5)+(visibleG[i]*visibleB[i]*1.3631399992049026E-6));
IJ.showProgress((float) i/dimension);
}

ImageStack outStack = new ImageStack(w, h);
outStack.addSlice("lw", lw);
outStack.addSlice("mw", mw);
outStack.addSlice("sw", sw);
outStack.addSlice("dbl", dbl);
new ImagePlus("Output", outStack).show();

}
}
