// Code automatically generated by 'Generate Cone Mapping Model' script by Jolyon Troscianko

//Model fits:
//lw 0.9997947470517686
//sw 0.9973119016835807


// Generated: 2019/4/8   13:18:26


import ij.*;
import ij.plugin.filter.PlugInFilter;
import ij.process.*;

public class Nikon_D7000_Nikkor_105mm_D65_to_Ferret_D65 implements PlugInFilter {

ImageStack stack;
	public int setup(String arg, ImagePlus imp) { 
	stack = imp.getStack(); 
	return DOES_32 + STACK_REQUIRED; 
	}
public void run(ImageProcessor ip) {

IJ.showStatus("Cone Mapping");
float[] vR;
float[] vG;
float[] vB;
float[] uB;
float[] uR;
int w = stack.getWidth();
int h = stack.getHeight();
int dimension = w*h;

float[] lw = new float[dimension];
float[] sw = new float[dimension];

vR = (float[]) stack.getPixels(1);
vG = (float[]) stack.getPixels(2);
vB = (float[]) stack.getPixels(3);
uB = (float[]) stack.getPixels(4);
uR = (float[]) stack.getPixels(5);

for (int i=0;i<dimension;i++) {
lw[i] = (float) (-0.0012561961495561804 +(vR[i]*3.4618069447539995E-4)+(vG[i]*0.009495379598914808)+(vB[i]*-5.580890636250406E-4)+(uB[i]*0.0011354507627690119)+(uR[i]*-4.965549181345323E-4)+(vR[i]*vG[i]*-3.4468486275838116E-6)+(vR[i]*vB[i]*1.3824182939177844E-6)+(vR[i]*uB[i]*-2.8317498150306134E-5)+(vR[i]*uR[i]*3.0427045514807796E-5)+(vG[i]*vB[i]*2.767138284967466E-6)+(vG[i]*uB[i]*4.815581830336032E-5)+(vG[i]*uR[i]*-5.2641405498605776E-5)+(vB[i]*uB[i]*-3.891461416136157E-6)+(vB[i]*uR[i]*5.237244385122084E-6)+(uB[i]*uR[i]*1.4372937286177654E-6));
sw[i] = (float) (0.003869154827436767 +(vR[i]*5.213059875471013E-4)+(vG[i]*-0.002581553575009587)+(vB[i]*0.008829837694714366)+(uB[i]*0.0075505793095657055)+(uR[i]*-0.004698213514200013)+(vR[i]*vG[i]*-6.57124391148346E-7)+(vR[i]*vB[i]*6.1158692531074355E-6)+(vR[i]*uB[i]*-5.146314690289133E-5)+(vR[i]*uR[i]*4.3916771223711844E-5)+(vG[i]*vB[i]*-8.59824634378374E-6)+(vG[i]*uB[i]*-1.4434220844906624E-4)+(vG[i]*uR[i]*1.5237936688435613E-4)+(vB[i]*uB[i]*3.448607297614951E-4)+(vB[i]*uR[i]*-3.4824562777565146E-4)+(uB[i]*uR[i]*1.0024838084365508E-5));
IJ.showProgress((float) i/dimension);
}

ImageStack outStack = new ImageStack(w, h);
outStack.addSlice("lw", lw);
outStack.addSlice("sw", sw);
new ImagePlus("Output", outStack).show();

}
}
