// Code automatically generated by 'Generate Cone Mapping Model' script by Jolyon Troscianko

//Model fits:
//lw 0.999768486548708
//mw 0.9999189987129296
//sw 0.9951282845790146
//uv 0.9977288487878435
//DblL1L3 0.9998818485228691


// Generated: 2019/3/3   21:30:43


import ij.*;
import ij.plugin.filter.PlugInFilter;
import ij.process.*;

public class Samsung_NX1000_Nikkor_EL_80mm_D65_to_guppy_Endler_300_700_1nm_tetra_D65 implements PlugInFilter {

ImageStack stack;
	public int setup(String arg, ImagePlus imp) { 
	stack = imp.getStack(); 
	return DOES_32 + STACK_REQUIRED; 
	}
public void run(ImageProcessor ip) {

IJ.showStatus("Cone Mapping");
float[] vR;
float[] vG;
float[] vB;
float[] uB;
float[] uR;
int w = stack.getWidth();
int h = stack.getHeight();
int dimension = w*h;

float[] lw = new float[dimension];
float[] mw = new float[dimension];
float[] sw = new float[dimension];
float[] uv = new float[dimension];
float[] DblL1L3 = new float[dimension];

vR = (float[]) stack.getPixels(1);
vG = (float[]) stack.getPixels(2);
vB = (float[]) stack.getPixels(3);
uB = (float[]) stack.getPixels(4);
uR = (float[]) stack.getPixels(5);

for (int i=0;i<dimension;i++) {
lw[i] = (float) (-4.1557089758692995E-4 +(vR[i]*5.949592440990005E-4)+(vG[i]*0.008927069371830588)+(vB[i]*-4.438192518001043E-4)+(uB[i]*8.246385716446145E-4)+(uR[i]*-5.2851315591888335E-6)+(vR[i]*vG[i]*-4.3251412720535995E-6)+(vR[i]*vB[i]*6.5662692413736295E-6)+(vR[i]*uB[i]*-2.9066721984689315E-5)+(vR[i]*uR[i]*2.8624585717696843E-5)+(vG[i]*vB[i]*-1.7441034732835394E-6)+(vG[i]*uB[i]*1.847463461868857E-5)+(vG[i]*uR[i]*-2.3192515669658258E-5)+(vB[i]*uB[i]*1.7986171110986647E-5)+(vB[i]*uR[i]*-1.3458618139867867E-5)+(uB[i]*uR[i]*1.3936363888839104E-6));
mw[i] = (float) (-5.757476697212945E-4 +(vR[i]*-5.455488183459116E-4)+(vG[i]*-9.922791214417722E-4)+(vB[i]*0.010235978820024047)+(uB[i]*7.649194757552444E-4)+(uR[i]*4.925950042508697E-4)+(vR[i]*vG[i]*-2.3635352517225636E-6)+(vR[i]*vB[i]*2.5204203995756788E-6)+(vR[i]*uB[i]*-2.2963249238723455E-6)+(vR[i]*uR[i]*-1.308304519942004E-6)+(vG[i]*vB[i]*-3.148120113094179E-7)+(vG[i]*uB[i]*-8.960391477932283E-6)+(vG[i]*uR[i]*1.3688390487030802E-5)+(vB[i]*uB[i]*2.0350154032229202E-5)+(vB[i]*uR[i]*-2.0260305080167603E-5)+(uB[i]*uR[i]*-6.057424385561177E-7));
sw[i] = (float) (0.003134746198341016 +(vR[i]*2.6687012019730924E-4)+(vG[i]*-0.0024055161469081748)+(vB[i]*0.006361097978331154)+(uB[i]*0.006040022738630451)+(uR[i]*-6.42269326768593E-4)+(vR[i]*vG[i]*-5.7577151036912325E-6)+(vR[i]*vB[i]*1.9557087293380924E-5)+(vR[i]*uB[i]*-6.22333034238529E-5)+(vR[i]*uR[i]*4.1796645485967585E-5)+(vG[i]*vB[i]*-1.738834770618992E-5)+(vG[i]*uB[i]*-8.029030599492294E-5)+(vG[i]*uR[i]*1.0433885685581302E-4)+(vB[i]*uB[i]*2.2592614608531202E-4)+(vB[i]*uR[i]*-2.2836443064400415E-4)+(uB[i]*uR[i]*6.051232261019039E-6));
uv[i] = (float) (-8.02209253443799E-4 +(vR[i]*2.7242485642620004E-4)+(vG[i]*-4.201383961567069E-4)+(vB[i]*6.212429534011057E-4)+(uB[i]*-0.005727169076915279)+(uR[i]*0.015053471741335093)+(vR[i]*vG[i]*-3.4510653492085622E-6)+(vR[i]*vB[i]*-2.0156480531380134E-6)+(vR[i]*uB[i]*2.2999783147028653E-5)+(vR[i]*uR[i]*-3.895707271283644E-5)+(vG[i]*vB[i]*2.236836700754836E-6)+(vG[i]*uB[i]*-6.390890052970358E-5)+(vG[i]*uR[i]*9.303993832264876E-5)+(vB[i]*uB[i]*4.243244007487955E-5)+(vB[i]*uR[i]*-4.163569946996801E-5)+(uB[i]*uR[i]*-9.523307714283328E-6));
DblL1L3[i] = (float) (-3.575886775850549E-4 +(vR[i]*5.0360768275793656E-5)+(vG[i]*0.008826400584946013)+(vB[i]*2.6050781137841036E-4)+(uB[i]*5.680843787192522E-4)+(uR[i]*2.2086894852355542E-4)+(vR[i]*vG[i]*-3.4074796708467735E-6)+(vR[i]*vB[i]*5.04839848454007E-6)+(vR[i]*uB[i]*-1.8274296806812677E-5)+(vR[i]*uR[i]*1.7311425545402766E-5)+(vG[i]*vB[i]*-1.3916662340319847E-6)+(vG[i]*uB[i]*8.223514922745934E-6)+(vG[i]*uR[i]*-1.0336604184015051E-5)+(vB[i]*uB[i]*1.6325086296109083E-5)+(vB[i]*uR[i]*-1.3429738559032565E-5)+(uB[i]*uR[i]*8.188481608926771E-7));
IJ.showProgress((float) i/dimension);
}

ImageStack outStack = new ImageStack(w, h);
outStack.addSlice("lw", lw);
outStack.addSlice("mw", mw);
outStack.addSlice("sw", sw);
outStack.addSlice("uv", uv);
outStack.addSlice("DblL1L3", DblL1L3);
new ImagePlus("Output", outStack).show();

}
}
