// Code automatically generated by 'Generate Cone Mapping Model' script by Jolyon Troscianko

//Model fits:
//lw 0.990953307624926
//mw 0.9911810390178546
//sw 0.997474609789049
//dbl 0.9942177352683879


// Generated: 2019/8/11   2:4:46


import ij.*;
import ij.plugin.filter.PlugInFilter;
import ij.process.*;

public class Test_Peafowl_LMS_D65_ implements PlugInFilter {

ImageStack stack;
	public int setup(String arg, ImagePlus imp) { 
	stack = imp.getStack(); 
	return DOES_32 + STACK_REQUIRED; 
	}
public void run(ImageProcessor ip) {

IJ.showStatus("Cone Mapping");
float[] visibleR;
float[] visibleG;
float[] visibleB;
int w = stack.getWidth();
int h = stack.getHeight();
int dimension = w*h;

float[] lw = new float[dimension];
float[] mw = new float[dimension];
float[] sw = new float[dimension];
float[] dbl = new float[dimension];

visibleR = (float[]) stack.getPixels(1);
visibleG = (float[]) stack.getPixels(2);
visibleB = (float[]) stack.getPixels(3);

for (int i=0;i<dimension;i++) {
lw[i] = (float) (-0.011877725026841326 +(visibleR[i]*0.008686967643932193)+(visibleG[i]*0.0011650589546311197)+(visibleB[i]*1.851123085174338E-4)+(visibleR[i]*visibleG[i]*5.846552878581461E-5)+(visibleR[i]*visibleB[i]*-4.4303975369188586E-5)+(visibleG[i]*visibleB[i]*-1.1389944673832819E-5));
mw[i] = (float) (2.90920360997684E-4 +(visibleR[i]*-9.785053198388695E-4)+(visibleG[i]*0.013272293819594588)+(visibleB[i]*-0.0024650773432371353)+(visibleR[i]*visibleG[i]*7.004429216250339E-6)+(visibleR[i]*visibleB[i]*1.9032863854979455E-5)+(visibleG[i]*visibleB[i]*-2.2996386250523832E-5));
sw[i] = (float) (-0.004494166576836596 +(visibleR[i]*1.897240845221576E-4)+(visibleG[i]*0.006379057931044001)+(visibleB[i]*0.004133842937471594)+(visibleR[i]*visibleG[i]*-3.903878095318134E-5)+(visibleR[i]*visibleB[i]*-3.0328400112263723E-5)+(visibleG[i]*visibleB[i]*6.206360978238949E-5));
dbl[i] = (float) (-0.0051627399870174595 +(visibleR[i]*0.0019325390393172299)+(visibleG[i]*0.008889912213005521)+(visibleB[i]*-9.274705086854675E-4)+(visibleR[i]*visibleG[i]*1.799377721689472E-5)+(visibleR[i]*visibleB[i]*-1.1031766793675608E-5)+(visibleG[i]*visibleB[i]*-3.8271692361308405E-6));
IJ.showProgress((float) i/dimension);
}

ImageStack outStack = new ImageStack(w, h);
outStack.addSlice("lw", lw);
outStack.addSlice("mw", mw);
outStack.addSlice("sw", sw);
outStack.addSlice("dbl", dbl);
new ImagePlus("Output", outStack).show();

}
}
