// Code automatically generated by 'Generate Cone Mapping Model' script by Jolyon Troscianko

//Model fits:
//lw NaN
//mw NaN
//sw NaN
//dbl NaN


// Generated: 2019/8/12   4:40:45


import ij.*;
import ij.plugin.filter.PlugInFilter;
import ij.process.*;

public class WorkshopTest_Bluetit_LMS_D65_ implements PlugInFilter {

ImageStack stack;
	public int setup(String arg, ImagePlus imp) { 
	stack = imp.getStack(); 
	return DOES_32 + STACK_REQUIRED; 
	}
public void run(ImageProcessor ip) {

IJ.showStatus("Cone Mapping");
float[]  ;
float[] visibleR;
float[] visibleG;
float[] visibleB;
int w = stack.getWidth();
int h = stack.getHeight();
int dimension = w*h;

float[] lw = new float[dimension];
float[] mw = new float[dimension];
float[] sw = new float[dimension];
float[] dbl = new float[dimension];

  = (float[]) stack.getPixels(1);
visibleR = (float[]) stack.getPixels(2);
visibleG = (float[]) stack.getPixels(3);
visibleB = (float[]) stack.getPixels(4);

for (int i=0;i<dimension;i++) {
lw[i] = (float) (NaN [i]+( [i]*NaN)+(visibleR[i]*NaN)+(visibleG[i]*NaN)+(visibleB[i]*NaN)+( [i]*visibleR[i]*NaN)+( [i]*visibleG[i]*NaN)+( [i]*visibleB[i]*NaN)+(visibleR[i]*visibleG[i]*NaN)+(visibleR[i]*visibleB[i]*NaN)+(visibleG[i]*visibleB[i]*NaN));
mw[i] = (float) (NaN [i]+( [i]*NaN)+(visibleR[i]*NaN)+(visibleG[i]*NaN)+(visibleB[i]*NaN)+( [i]*visibleR[i]*NaN)+( [i]*visibleG[i]*NaN)+( [i]*visibleB[i]*NaN)+(visibleR[i]*visibleG[i]*NaN)+(visibleR[i]*visibleB[i]*NaN)+(visibleG[i]*visibleB[i]*NaN));
sw[i] = (float) (NaN [i]+( [i]*NaN)+(visibleR[i]*NaN)+(visibleG[i]*NaN)+(visibleB[i]*NaN)+( [i]*visibleR[i]*NaN)+( [i]*visibleG[i]*NaN)+( [i]*visibleB[i]*NaN)+(visibleR[i]*visibleG[i]*NaN)+(visibleR[i]*visibleB[i]*NaN)+(visibleG[i]*visibleB[i]*NaN));
dbl[i] = (float) (NaN [i]+( [i]*NaN)+(visibleR[i]*NaN)+(visibleG[i]*NaN)+(visibleB[i]*NaN)+( [i]*visibleR[i]*NaN)+( [i]*visibleG[i]*NaN)+( [i]*visibleB[i]*NaN)+(visibleR[i]*visibleG[i]*NaN)+(visibleR[i]*visibleB[i]*NaN)+(visibleG[i]*visibleB[i]*NaN));
IJ.showProgress((float) i/dimension);
}

ImageStack outStack = new ImageStack(w, h);
outStack.addSlice("lw", lw);
outStack.addSlice("mw", mw);
outStack.addSlice("sw", sw);
outStack.addSlice("dbl", dbl);
new ImagePlus("Output", outStack).show();

}
}
